module.exports = {
  apps: [{
    name: 'wspreminder-backend',
    script: 'index.js',
    instances: 1,
    exec_mode: 'fork',
    watch: false,
    max_memory_restart: '500M',
    max_restarts: 10,
    min_uptime: '10s',
    restart_delay: 5000,
    exp_backoff_restart_delay: 100,
    kill_timeout: 10000,
    listen_timeout: 30000,
    shutdown_with_message: true,
    env: {
      NODE_ENV: 'production',
      LOG_LEVEL: 'info',
    },
    error_file: './logs/error.log',
    out_file: './logs/out.log',
    combine_logs: true,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  }],
}
